### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by the-oem** [the-oem/2DoBox-Pivot#13]
We’d like our users to be able to easily find specific TODOs they’ve already created, so let’s provide them with a filtering interface on the TODO list.

- At the top of the TODO list, include a text field labeled Filter.
- As a user types in the filter box, the list of TODOs should filter in real time to only display TODOs whose title or task include the user’s text.
- The page should not reload.
- Clearing the filter box should restore all the ideas to the list.

**Comment by kristing40** [comment]
Got it.
